title: Joselito Rapisora
author:
  name: "Joselito Rapisora"
  email: "joselito.rapisora@gmail.com"
description: Everyone I meet was sent my way to teach me something.
baseurl: ""
url: "https://joselitorapisora.github.io"

# Minima theme settings
theme: minima
minima:
  skin: classic
  social_links:
  - { platform: github, icon: github, user_url: "https://github.com/joselitorapisora" }

# Show excerpts on the homepage
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag  
header_pages:
  - about.md